day13/Ecomm/Estore/Models/ErrorViewModel.cs
namespace Estore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

day13/Ecomm/Estore/Controllers/DepartmentsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Estore.Models;
using BusinessLogicLayer;
using BusinessObjectLayer;

namespace Estore.Controllers;

public class DepartmentsController : Controller
{
    private readonly ILogger<DepartmentsController> _logger;

    public DepartmentsController(ILogger<DepartmentsController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    { HRManger HRM=new HRManger();
        List<Department> depts=HRM.GetallDept();
        ViewData["depts"]=depts;
        return View();
    }
}

day13/Ecomm/Estore/Controllers/EmployeesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Estore.Models;
using BusinessLogicLayer;
using BusinessObjectLayer;

namespace Estore.Controllers;

public class EmployeesController : Controller
{
    private readonly ILogger<EmployeesController> _logger;

    public EmployeesController(ILogger<EmployeesController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index(int id)
    {  Console.WriteLine(id);
        HRManger HRM=new HRManger();
        List<Employee> emp=HRM.allEmpDetails(id);
        ViewData["emps"]=emp;
        return View();
    }
}

day13/Ecomm/Estore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Estore.Models;

namespace Estore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

day13/Ecomm/Estore/Controllers/ProductsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Estore.Models;
using BusinessLogicLayer;
namespace Estore.Controllers;
using BusinessObjectLayer;

public class ProductsController : Controller
{
    private readonly ILogger<ProductsController> _logger;

    public ProductsController(ILogger<ProductsController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        CatalogManager CM=new CatalogManager();

        List<Product> list=CM.GetAllProduct();
    //    CM.InsertProducts(list);
        ViewData["List"]=list;

        return View();
    }

    public IActionResult Details(int id){
    CatalogManager CM=new CatalogManager(); 
      ViewData["product"]=(Product)CM.GetProdctById(id);
      return View();
    }


   public IActionResult AddData(){
    Product newProd=new Product();
    return View();
   }

    [HttpPost]
    public IActionResult AddData(Product prod){
        List<Product> prods=new List<Product>();
        prods.Add(prod);
        CatalogManager CM=new CatalogManager(); 
        CM.InsertProducts(prods);
        return Redirect("Index");
    }

}

day13/Ecomm/Estore/Views/Departments/Index.cshtml
@using BusinessObjectLayer;
@{
    ViewData["Title"] = "Index Page";
}

<div class="text-center">
    <h1 class="display-4">Departments</h1>
    @{
        List<Department> dept=(List<Department>)ViewData["depts"];
            <ol>
                @foreach (Department item in dept)
                {
                    <li><a href="/Employees/Index/@item.Id">@item.Name</a></li>
                    
                }
            </ol>
     }
  
</div>

day13/Ecomm/Estore/Views/Employees/Index.cshtml
@using BusinessObjectLayer;
@{
    ViewData["Title"] = "Index Page";
}

<div class="text-center">
    <h1 class="display-4">Departments</h1>
    @{
        List<Employee> emps=(List<Employee>)ViewData["emps"];
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">FirstName</th>
      <th scope="col">LastName</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
     <th scope="col">DeptId</th>
    </tr>
  </thead>
  <tbody>
    @foreach (Employee item in emps)
    {
    <tr>
      <th scope="row">@item.Id</th>
      <td>@item.FirstName</td>
      <td>@item.LastName</td>
      <td>@item.Email</td>
      <td>@item.Address</td> 
      <td>@item.DeptId</td>
    </tr>
    }
    
  </tbody>
</table>
           
     }
  
</div>

day13/Ecomm/Estore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

day13/Ecomm/Estore/Views/Products/AddData.cshtml
@using BusinessObjectLayer;
@model Product;
@{
    ViewData["Title"] = "AddProduct Page";
}

<form action="/Products/AddData" method="POST">
  <div class="form-group">
    <label for="exampleInputEmail1">Product id</label>
    <input type="number" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" asp-for="Pid">
    @* <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> *@
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Product Name</label>
    <input type="text" class="form-control" id="exampleInputPassword1" asp-for="Pname">
  </div>
   <div class="form-group">
    <label for="desc">Description</label>
    <input type="text" class="form-control" id="desc" asp-for="Description">
  </div>
   <div class="form-group">
    <label for="price">Price</label>
    <input type="number" class="form-control" id="price" asp-for="Price">
  </div>
   <div class="form-group">
    <label for="qty">Quantity</label>
    <input type="number" class="form-control" id="qty" asp-for="Quntity">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

day13/Ecomm/Estore/Views/Products/Details.cshtml
@using BusinessObjectLayer;
@{
    ViewData["Title"] = "Details Page";
}

<div class="text-center">
    <h1 class="display-4">Product</h1>
    @{
         Product p=(Product)ViewData["product"];
        <p>Product id: <b>@p.Pid</b></p>
        <p>Product Name: <b> @p.Pname</b></p>
        <p>Product Price: <b> @p.Price</b></p>
        <p>Product Quntity:<b> @p.Quntity</b></p>
        <p>Product Description:<b> @p.Description</b></p>
        <a href="#">AddToCart</a>
    }
    
  
</div>

day13/Ecomm/Estore/Views/Products/Index.cshtml
@using BusinessObjectLayer;
@{
    ViewData["Title"] = "Product List Page";
}

<div class="text-center">
    <h1 class="display-4">Products</h1>
    @{
        List<Product> Products=(List<Product>)ViewData["list"];
            <a href="/products/AddData"><button type="button" name="btn" id="btn">AddProduct</button></a>

        <ol>
            @foreach(Product prod in Products){
                <li><a href="/Products/Details/@prod.Pid">@prod.Pname</a></li>
            }
        </ol>
    }
    
</div>

day13/Ecomm/Estore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Estore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Estore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Estore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">ProductGallary</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Estore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>